name: Build

on:
  workflow_dispatch: ~
  push:
    branches:
      - main
    paths:
      - src/**

jobs:
  build:
    name: Build and push image onto dockerhub and ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm and dependencies
        uses: pnpm/action-setup@v2.2.2
        with:
          run_install: true
      - name: Build project
        run: pnpm build
      - uses: wdzeng/image@feats/format
        with:
          dockerhub: false
          tag-format: linlee-$VERSION
          build-target: linlee
          image: pooptest
      - uses: wdzeng/image@feats/format
        with:
          dockerhub: false
          image: pooptest
  tag:
    name: Add tags to repository
    if: ${{ github.event_name == 'push' }}
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: version
        uses: wdzeng/version@v1
        with:
          prefix: v
      - name: Add tags
        run: |
          git tag -f ${{ steps.version.outputs.version }} main && \
          git push -f origin ${{ steps.version.outputs.version }}
